### ISSUE TITLE
adding "download the transcript files" checkbox

### ISSUE THREAD

**Issue by elakhdarayoub** [ahmedayman4a/Linkedin-Learning-Courses-Downloader.UpdateManager#1]
hi ahmed, this app rocks thanks for sharing, it would be awesome if you added the adding the ability to choose weather to download the transcript files ( .srt / .vtt ) or not, like you did with the **download exercise files** checkbox.
also hoping if you can work on the front end a little bit, thanks a lot.

**Comment by ahmedayman4a** [comment]
Added this feature with [version 1.2](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/releases/tag/v1.2).
